collections:
  - name: community.general
  - name: ansible.posix
  - name: community.docker # Required for geerlingguy.docker role
  - name: community.libvirt
  - name: kubernetes.core
  - name: ansible.windows
